version: '3.3'
services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
    links:
      - web
    ports:
      - '80:80'
    restart: always
  mongo:
    container_name: 'mongo'
    image: mongo:5.0-focal
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/config:/data/configdb
    restart: always
  api:
    container_name: api
    links:
      - mongo
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: 5000
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 100
      MONGO_URI: 'mongodb://mongo:27017/dizzy'
      ES_URI: 'http://10.4.8.146:9200'
      ES_PING_TIMEOUT_MS: 20000
      ES_INDEX: 'crawlers_v4'
      JWT_SECRET: 'UJl5Y8nK7b7TNjz8'
      JWT_EXPIRE_DAYS: '30d'
      JWT_COOKIE_EXPIRE_MS: 2592000000
      LOGOUT_COOKIE_EXPIRE_MS: 10000
      RESET_PASSWORD_EXPIRE_MS: 600000
      SMTP_HOST: 'smtp.mailtrap.io'
      SMTP_PORT: 2525
      SMTP_EMAIL: '19ff6cf1be8f11'
      SMTP_PASSWORD: 'd90003bf257b39'
      FROM_EMAIL: 'no-reply@dizzy.cibr.qcri.org'
      FROM_NAME: 'Dizzy'
    ports:
      - '5000:5000'
    restart: always
  web:
    container_name: web
    depends_on:
      - api
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: 'production'
    ports:
      - '3000:80'
    restart: always
