version: '3.3'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    links:
      - web
    ports:
      - '80:80'
  mongo:
    container_name: 'mongo'
    image: mongo:4.0.4
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  api:
    container_name: api
    links:
      - mongo
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/app
      - api-node-modules:/app/node_modules
    environment:
      NODE_ENV: 'developement'
      HOST: '0.0.0.0'
      PORT: 5000
      RATE_LIMIT_WINDOW_MS: 60000
      RATE_LIMIT_MAX: 100
      MONGO_URI: 'mongodb://mongo:27017/dizzy'
      ES_URI: 'http://10.4.8.146:9200'
      ES_PING_TIMEOUT_MS: 20000
      ES_INDEX: 'crawlers_v4'
      JWT_SECRET: 'UJl5Y8nK7b7TNjz8'
      JWT_EXPIRE_DAYS: '30d'
      JWT_COOKIE_EXPIRE_MS: 2592000000
      LOGOUT_COOKIE_EXPIRE_MS: 10000
      RESET_PASSWORD_EXPIRE_MS: 600000
      SMTP_HOST: 'smtp.mailtrap.io'
      SMTP_PORT: 2525
      SMTP_EMAIL: '19ff6cf1be8f11'
      SMTP_PASSWORD: 'd90003bf257b39'
      FROM_EMAIL: 'no-reply@dizzy.cibr.qcri.org'
      FROM_NAME: 'Dizzy'
    ports:
      - '5000:5000'
  web:
    container_name: web
    depends_on:
      - api
    stdin_open: true
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - ./web:/app
      - web-node-modules:/app/node_modules
    environment:
      NODE_ENV: 'developement'
    ports:
      - '3000:3000'

volumes:
  mongo-data:
  api-node-modules:
  web-node-modules:
