FROM node:14-alpine as base
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN apk add --no-cache --virtual .gyp python3 make g++ \
    && apk update \
    && npm ci && npm cache clean --force \
    && apk del .gyp

FROM base as build
COPY . .
RUN npm run build

FROM nginx:1-alpine as serve
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf